baseurl             = "https://martinos.github.com/blog"
builddrafts         = false
canonifyurls        = false
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "docs"
theme               = "cocoa-hugo-theme"
author              = "Martin Chabot"
title               = "Martin Chabot"
pygmentsuseclasses  = true
disqusshortname     = "blog-martinosis-com" # Comment out to disable Disqus.
pluralizelisttitles = false
googleAnalytics     = "UA-100550318-1"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "About"
weight                 = -110
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = "Code"
weight                 = -100
identifier             = "code"
url                    = "/code/"

[params]
latestpostscount       = 5                             # how many posts to display on the home page
i18n_flags             = false                         # whether to display small country flags for available translations
author                 = "Martin Chabot"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Don't panic"
# email                  = "you@example.space"
extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
faviconfile            = "img/leaf.ico"
github                 = "//github.com/martinos"
highlightjs            = true
lang                   = "en"
linkedin               = "//linkedin.com/in/martin-chabot-0377623"
noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
selfintro              = ""                            # appears in the site header when set to a non-empty string
twitter                = "//twitter.com/martinosis"
# mastodon               = "//example.com/@you"
highlightjslanguages = ["ruby"]                        # additional languages not included in the "common" set
# highlightjsStyle     = "darcula"

piwik				   = false                         # If true, Piwik integration is enabled
# piwik_url            = "//www.example.com/piwik/"    # URL to your Piwik installation. Must End with a slash
# piwik_id			   = 2                             # Id of your site in Piwik

# avatar                 = "img/profile.png" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar) */
gravatar                 = "ed77c0d1c8da409c4f69f67f934ff0bb" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar) */

